sudo: required
services:
  - docker
before_install:
  - docker build -t ddydeveloper/angular6-test-app .
  - docker run -d -p 127.0.0.1:80:4567 ddydeveloper/angular6-test-app /bin/sh -c "cd /root/angular6-test-app; bundle exec foreman start;"
  - docker ps -a
  - docker run ddydeveloper/angular6-test-app /bin/sh -c "cd /root/angular6-test-app; bundle exec rake test"
script:
  - bundle exec rake test