sudo: required
services:
  - docker

before_install:
  - npm install -g @angular/cli
  - npm install
  # - docker build -t ddydeveloper/angular6-test-app .

script:
  # - docker run -t ddydeveloper/angular6-test-app npm run test
  - npm run test
  - npm run prod