sudo: required
services:
  - docker

script:
  - docker build -t ddydeveloper/angular6-test-app .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push ddydeveloper/angular6-test-app
  on:
    branch: master