sudo: required
services:
  - docker

before_install:
  - npm install @angular/cli
  - docker build -t ddydeveloper/angular6-test-app .

script:
  - npm run test
  - docker run -t ddydeveloper/angular6-test-app