language: node_js
sudo: required
services:
  - docker
cache:
   directories:
     - node_modules
node_js:
  - 8
before_install:
  - npm install -g @angular/cli
  - docker build -t ddydeveloper/angular6-test-app .
script:
  - docker run -t ddydeveloper/angular6-test-app npm run test